const express = require('express')
const router = express.Router()
const controller = require('../controllers/employee.controller')

router.get('/index',controller.index)
router.get('/newEmployee',controller.create_employee_page)
router.post('/newEmployee',controller.create_employee)
router.get('/newProject',controller.create_Project_page)
router.post('/newProject',controller.create_Project)
router.get('/project/:id',controller.get_project_details)
router.get('/employee/:id',controller.get_employee_details)
router.delete('/project/:id',controller.delete_project)
router.delete('/employee/:id',controller.delete_employee)
