name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on:
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16.15.0
        cache: 'npm'
    - run: cd frontend
    - run: npm install --legacy-peer-deps
    - run: npm run build --if-present
    - run: npm test
