name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:   [ubuntu-latest, windows-latest, macOS-latest]
      
    
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey! This is your first Issue!' Thanks for Contributing"
        pr-message: "Hey! this is your first Pull Request!' Thanks for Contributing"
